### PR TITLE
Include Cargo Publish step

### PR DESCRIPTION
**Pull request by medallyon**
This should automatically publish the package to cargo. Addresses #666

### CODE REVIEW

**Comment by Kampfkarren** [comment]
1. Rojo doesn't actually publish anymore ever since the switch from subdependencies to Wally
2. Unless this is already set from something else, current key holders don't actually have access to the crates.io package.

**Comment by boatbomber** [comment]
We have switched back to submodules so that is unblocked, although we still don't have crate access.

**Comment by Dekkonot** [comment]
@Kampfkarren Given that both items in your list are resolved now, what does the status of this look like?

**Comment by Dekkonot** [comment]
We'll revisit this if it becomes wanted or needed, but right now I'm not prioritizing automating cargo releases.

**Pull request closed without merging**
