### PR TITLE
Changed the baseplate and added texture

### PR DESCRIPTION
**Pull request by VillaErnest**
- Updated the baseplate size and position
- Added the default baseplate texture

**Before**
RobloxScreenShot20220727_210718096

**After**
RobloxScreenShot20220727_210736830

### CODE REVIEW

**Comment by Kampfkarren** [comment]
Class names are not necessary. It's good the default project format doesn't falsely teach that it is. 

I could've sworn the other changes have been denied in the past, but can't find the PR.

**Comment by VillaErnest** [comment]
> Class names are not necessary. It's good the default project format doesn't falsely teach that it is.
> 
> I could've sworn the other changes have been denied in the past, but can't find the PR.
I see, I added the class names because Selene is giving me the warning to do so.

**Comment by Kampfkarren** [comment]
Not selene, the Rojo extension, which is incorrect.

**Comment by VillaErnest** [comment]
> Not selene, the Rojo extension, which is incorrect.

Is it possible to silence this warning?

**Comment by LPGhatguy** [comment]
Hello, thanks for the PR!

I think that this is a good change to the default project. However, it also makes the starting `default.project.json` file a fair bit bigger. A fair number of users complain about the default project having a baseplate, and having that baseplate in the project file _is_ kinda weird.

I think that we should consider making the default project have an `rbxm` file or `model.json` containing the baseplate to clear up this clutter.

What do y'all think, @VillaErnest, @Kampfkarren?

**Comment by VillaErnest** [comment]
> Hello, thanks for the PR!
> 
> I think that this is a good change to the default project. However, it also makes the starting `default.project.json` file a fair bit bigger. A fair number of users complain about the default project having a baseplate, and having that baseplate in the project file _is_ kinda weird.
> 
> I think that we should consider making the default project have an `rbxm` file or `model.json` containing the baseplate to clear up this clutter.
> 
> What do y'all think, @VillaErnest, @Kampfkarren?

I agree, having the baseplate inside the `default.project.json` file seems weird and out of place. So, making a separate `rbxm` file should make the `default.project.json` file less cluttered.

**Comment by Dekkonot** [comment]
Closing to clean up old PRs. Sorry! Feel free to re-open if it's still something we need or you want changed.

**Pull request closed without merging**
