### PR TITLE
Add file paths to /api/read via querystring

### PR DESCRIPTION
**Pull request by jerrin-foster**
Fulfills #335

### CODE REVIEW

**Comment by Muoshuu** [comment]
Temporary solution while we wait for a more solid HTTP API, but should make external tooling for Rojo a bit more powerful.

**Comment by Muoshuu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Teotcd** [comment]
This feature allows for a whole host of tools to be enabled in relation to the seperate plugin "Rojo UI".
If an admin could review this pull request that's been here since June, that'd be great!

**Comment by sasial-dev** [comment]
@Muoshuu, you'll need to rebase this for 7.0.0-alpha.1

**Comment by sasial-dev** [comment]
CC @LPGhatguy 
This is getting stale!

**Comment by Dekkonot** [comment]
Closing to clean up old PRs. Sorry!

**Pull request closed without merging**
