### PR TITLE
Change Notification sound to generic sound

### PR DESCRIPTION
**Pull request by imacodr**
The notification sound for the plugin notifications causes the game to summon an error due to no experience permissions with no way to grant permission. This is due to the new audio policy update.

### CODE REVIEW

**Comment by boatbomber** [comment]
I think the sound file in assets/ should be replaced as well to create consistency between our repo assets and the used assets.

**Comment by LPGhatguy** [comment]
I don't know if this sound fits. What other notification sounds are available that will work?

**Comment by boatbomber** [comment]
How about [203785492](https://www.roblox.com/library/203785492/Pop-Close-Sound)?

**Comment by LPGhatguy** [comment]
> How about [203785492](https://www.roblox.com/library/203785492/Pop-Close-Sound)?

Works for me!

**Comment by imacodr** [comment]
Sounds good

**Review by LPGhatguy — APPROVED** [review]
LGTM.

**Pull request merged**
