### PR TITLE
Support ambiguous syntax for Font properties

### PR DESCRIPTION
**Pull request by Dekkonot**
Given how unambiguous `Font` as a datatype actually is, it makes not very much sense to require people use the fully qualified syntax for `FontFace` and any other properties that come up. So, this PR adds a new ambiguous syntax that supports it.

Long-term, I think we should reconsider our strategy for font families to make it more obvious how to set them (maybe use an enum instead of a raw string?) but that's an issue for another day.

### CODE REVIEW

**Comment by kennethloeffler** [comment]
> Long-term, I think we should reconsider our strategy for font families to make it more obvious how to set them (maybe use an enum instead of a raw string?) but that's an issue for another day.

The `Font` type in Roblox's Lua API also uses content URIs for font families, so I don't think it will be too surprising, as long as it's documented!

**Comment by Dekkonot** [comment]
I don't think it's surprising necessarily, it's just rather inconvenient to have to specify a path to a JSON! Roblox offers `Font.fromEnum` and `Font.fromName` as convenience functions and I think it'd be nice to have something similar for Rojo users. That's out of scope for this PR though.

**Comment by Dekkonot** [comment]
bruh.

**Comment by Hedreon** [comment]
Would love for this to be merged.

**Review by kennethloeffler — APPROVED** [review]
Tested building an rbxm from
```json
{
  "name": "TextBox",
  "tree": {
    "$className": "TextBox",
    "$properties": {
      "FontFace": {
        "family": "rbxasset://fonts/families/RobotoMono.json",
        "weight": "Thin",
        "style": "Normal"
      }
    }
  }
}
```
and was successful, lgtm

**Review by boatbomber — APPROVED** [review]

**Pull request merged**
